version: "3.8"

services:
  mlflow-postgres:
    container_name: mlflow-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./mlflow_pgdata:/var/lib/postgresql/data
    networks:
      - nginx-network

  mlflow-tracking:
    container_name: mlflow-tracking
    image: custom/mlflow-tracking:latest
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    restart: unless-stopped
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-tracking:5000
      BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:5432/${POSTGRES_DB}
      ARTIFACT_ROOT: s3://${MLFLOW_ARTIFACT_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:5432/${POSTGRES_DB}
      --default-artifact-root s3://${MLFLOW_ARTIFACT_BUCKET}
      --host 0.0.0.0
      --port 5000
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
    driver: bridge
